# Generated by Django 5.0.1 on 2024-03-05 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='cars',
            name='cubic_capacity',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='variant',
        ),
        migrations.AddField(
            model_name='cars',
            name='Registration',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cars',
            name='brand_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='store.brand'),
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel_object',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='store.fuel'),
        ),
    ]
