# Generated by Django 5.0.1 on 2024-03-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_fuel_remove_cars_cubic_capacity_remove_cars_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteitems',
            name='added',
        ),
    ]
