# Generated by Django 5.0.1 on 2024-03-24 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_favouriteitems_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('total', models.PositiveIntegerField()),
                ('order_id', models.CharField(max_length=200, null=True)),
                ('payment', models.CharField(choices=[('cod', 'cod'), ('online', 'online')], default='cod', max_length=200)),
                ('status', models.CharField(choices=[('order-booked', 'order-booked'), ('cancelled', 'cancelled')], default='order-booked', max_length=200)),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_item_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.favouriteitems')),
                ('order_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseitems', to='store.booking')),
            ],
        ),
    ]
