# Generated by Django 5.0.1 on 2024-03-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_booking_bookingitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment',
            field=models.CharField(default='online', max_length=200),
        ),
    ]
