# Generated by Django 5.0.1 on 2024-03-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_booking_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total',
        ),
    ]
