# Generated by Django 5.0.1 on 2024-03-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_booking_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteitems',
            name='is_order_placed',
            field=models.BooleanField(default=False),
        ),
    ]
